#!/bin/sh

#   Copyright (C) 2004 University of Oxford
#
#   SHCOPYRIGHT


echo
echo "Warning - bedpost has been deprecated! Please use bedpostX instead."
[ -z "$@" ] && ${FSLDIR}/bin/bedpostX
echo "Executing \"bedpostX $@ -n 1\" instead."
echo
${FSLDIR}/bin/bedpostX $@ -n 1
