#!/bin/sh

if [ $1 = "" ]; then 
    echo "Usage: $0 data directory"
    exit;
fi

DIR=$1;
for img in ${DIR}/data ${DIR}/nodif ${DIR}/nodif_brain_mask ;do
    if [ `imtest $img` -eq 1 ] ; then
	echo $img
	avwinfo $img;
	echo ""
    else
	echo $img does not exist;
    fi
done

for bv in ${DIR}/bvals ${DIR}/bvecs;do
    echo " num lines in $bv "
    cat $bv|wc -l
    echo " num words in $bv "
    cat $bv|wc -w
done