#!/bin/sh
#   Copyright (C) 2012 University of Oxford
#
#   SHCOPYRIGHT

if [ $# -lt 1 ]; then
echo "Usage: facalc <basename> [-mode]"
echo "e.g. facalc dti "
echo "This will use dti_L1 dti_L2 and dti_L3 to compute dti_FA"
echo "If -mode is set, the mode is calculated as well"
echo "Usage: facalc basename outbase"
echo "e.g. facalc dti test"
echo "will write test_FA instead of dti_FA"
exit
fi

bn=$1
if [ $# -lt 2 ];then 
ob=$bn
else
if [ "$2" != -mode ];then
ob=$2
else
ob=$bn
fi
fi


if [ `${FSLDIR}/bin/imtest ${bn}_L1` -eq 0 -o  `${FSLDIR}/bin/imtest ${bn}_L2` -eq 0 -o `${FSLDIR}/bin/imtest ${bn}_L3` -eq 0 ];
then echo "Not all eigenvalue images exist"
echo "stopping"
exit
fi


${FSLDIR}/bin/fslmaths ${bn}_L1 -add ${bn}_L2 -add ${bn}_L3 -div 3 tmpMD
${FSLDIR}/bin/fslmaths ${bn}_L1 -sqr tmpL1sq
${FSLDIR}/bin/fslmaths ${bn}_L2 -sqr tmpL2sq
${FSLDIR}/bin/fslmaths ${bn}_L3 -sqr tmpL3sq
${FSLDIR}/bin/fslmaths ${bn}_L1 -sub tmpMD -sqr tmpl1subsq
${FSLDIR}/bin/fslmaths ${bn}_L2 -sub tmpMD -sqr tmpl2subsq
${FSLDIR}/bin/fslmaths ${bn}_L3 -sub tmpMD -sqr tmpl3subsq
${FSLDIR}/bin/fslmaths tmpL1sq -add tmpL2sq -add tmpL3sq denom
${FSLDIR}/bin/fslmaths tmpl1subsq -add tmpl2subsq -add tmpl3subsq -mul 1.5 numer
${FSLDIR}/bin/fslmaths numer -div denom -sqrt ${ob}_FA

if [ "$2" == -mode -o "$3" == -mode ];then
    ${FSLDIR}/bin/fslmaths ${bn}_L1 -sub tmpMD tmpE1
    ${FSLDIR}/bin/fslmaths ${bn}_L2 -sub tmpMD tmpE2
    ${FSLDIR}/bin/fslmaths ${bn}_L3 -sub tmpMD tmpE3
    ${FSLDIR}/bin/fslmaths tmpE3 -mul -2 -add tmpE1 -add tmpE2 tmpN1 
    ${FSLDIR}/bin/fslmaths tmpE1 -mul -2 -add tmpE2 -add tmpE3 tmpN2 
    ${FSLDIR}/bin/fslmaths tmpE2 -mul -2 -add tmpE1 -add tmpE3 tmpN3 
    ${FSLDIR}/bin/fslmaths tmpN1 -mul tmpN2 -mul tmpN3 -mul -1 tmpN

    ${FSLDIR}/bin/fslmaths tmpE1 -sub tmpE2 -sub tmpE3 -mul tmpE1 tmpD
    ${FSLDIR}/bin/fslmaths tmpE2 -sub tmpE3 -mul tmpE2 -add tmpD tmpD
    ${FSLDIR}/bin/fslmaths tmpE3 -mul tmpE3 -add tmpD
    ${FSLDIR}/bin/fslmaths tmpD -thr 0 -sqrt tmpD
    ${FSLDIR}/bin/fslmaths tmpD -mul tmpD -mul tmpD -mul 2 tmpD

    ${FSLDIR}/bin/fslmaths tmpN -div tmpD -max -1 -min 1 ${ob}_MO
fi

${FSLDIR}/bin/imrm tmpMD tmpL1sq tmpL2sq tmpL3sq tmpl1subsq tmpl2subsq tmpl3subsq numer denom tmpE1 tmpE2 tmpE3 tmpD tmpN1 tmpN2 tmpN3






