#!/bin/sh

# Check for display being set \
if [ X`uname | grep CYGWIN`X = XX ] ; then
    #\
    if [ _$DISPLAY = _ ] ; then
        #\
	echo "DISPLAY is not set. Please set your DISPLAY environment variable!"
        #\
	exit 1
    #\
    fi
#\
fi

# the next line restarts using wish \
exec $FSLDIR/bin/tixwish "$0" "$@"

set INMEDX 0
set FSLDIR $env(FSLDIR)

set origname [ string tolower [ file tail [ info script ] ] ]

set UNAME [ exec uname ]
if { $UNAME == "Darwin" || [ string compare CYGWIN [ string range $UNAME 0 5 ] ] == 0 } {
    regsub "_gui" $origname "" origname
}

source ${FSLDIR}/tcl/${origname}.tcl

exit
