#!/bin/sh

# Copyright (C) 2007 University of Oxford
#
# SHCOPYRIGHT

Usage() {
    echo ""
    echo "Usage: maskdyads dyads fsamples [thr]"
    echo "default value for thr is 0.05"
    exit
}

[ "$1" = "" ] && Usage

d=`$FSLDIR/bin/remove_ext $1`
f=$2
t=0.05

if [ "$3" != "" ] ; then
    t=$3
fi

tmpfile=`$FSLDIR/bin/tmpnam`
$FSLDIR/bin/fslmaths $f -thr $t -bin $tmpfile
$FSLDIR/bin/fslmaths $d -mul $tmpfile ${d}_thr$t


