#!/bin/sh

#   Copyright (C) 2004 University of Oxford
#
#   SHCOPYRIGHT

Usage(){
    echo "bedpostX_kill_pid <pid>"
    echo ""
    echo "<pid> is the pid of the bedpostX_proc"
    echo "kills this process + all diff_pvm children"
    echo ""
    exit
}

[ "$1" = "" ] && Usage
pid=$1

i=`ps -fU  $USER |grep -v grep | grep xfibres |grep ${pid}| awk '{print $2}'`
kill -KILL $pid $i 

