#!/bin/sh

#   Copyright (C) 2004 University of Oxford
#
#   SHCOPYRIGHT

Usage() {
    echo ""
    echo "Usage: bedpost_proc <subject_dir> <nslices> [piddir]"
    echo ""
    exit
}


[ "$2" = "" ] && Usage
[ "$3" = "" ] || touch ${3}/`hostname`_fdt_${$}


subjdir=$1
nslices=$2



slice=0
while [ $slice -lt $nslices ];do
    slicezp=`${FSLDIR}/bin/zeropad $slice 4`
    if [ ! -e ${subjdir}.bedpost/logs/.$slicezp ] ; then
	echo `hostname`_${$} > ${subjdir}.bedpost/logs/.$slicezp
	sleep 10
	if [ `hostname`_${$} = `cat ${subjdir}.bedpost/logs/.$slicezp | sed -n '1p'` ] ; then
	    nice ${FSLDIR}/bin/diff_pvm --data=${subjdir}/data_slice_$slicezp --mask=${subjdir}/nodif_brain_mask_slice_$slicezp -b ${subjdir}/bvals -r ${subjdir}/bvecs --logdir=${subjdir}.bedpost/diff_slices/data_slice_$slicezp --nj=1300 --bi=300 --se=20 > ${subjdir}.bedpost/logs/log$slicezp
	    touch ${subjdir}.bedpost/logs/.${slicezp}_finished
	fi
    fi
    slice=`echo "$slice + 1" | bc`
done

[ "$3" = "" ] || rm ${3}/`hostname`_fdt_${$}
sleep 10