#!/bin/sh

#   Copyright (C) 2004 University of Oxford
#
#   SHCOPYRIGHT

Usage() {
    echo ""
    echo "Usage: bedpostX_proc <subject_dir> <nslices> [piddir]"
    echo ""
    exit
}


[ "$2" = "" ] && Usage
[ "$3" = "" ] || touch ${3}/`hostname`_fdt_${$}


subjdir=$1
nslices=$2



slice=0
while [ $slice -lt $nslices ];do
    slicezp=`${FSLDIR}/bin/zeropad $slice 4`
    if [ ! -f ${subjdir}.bedpostX/logs/.$slicezp ] ; then
	echo `hostname`_${$} > ${subjdir}.bedpostX/logs/.$slicezp
	sleep 10
	if [ `hostname`_${$} = `cat ${subjdir}.bedpostX/logs/.$slicezp | sed -n '1p'` ] ; then
	    nice ${FSLDIR}/bin/xfibres --data=$subjdir/data_slice_$slicezp --mask=$subjdir/nodif_brain_mask_slice_$slicezp -b $subjdir/bvals -r $subjdir/bvecs --forcedir --logdir=$subjdir.bedpostX/diff_slices/data_slice_$slicezp --nj=1000 --bi=600 --bn=0 --se=20 --nfibres=2 --fudge=1.5> $subjdir.bedpostX/logs/log$slicezp 
#bi can be changed to 2000 if convergence looks dodgy
	    touch ${subjdir}.bedpostX/logs/.${slicezp}_finished
	fi
    fi
    slice=`echo "$slice + 1" | bc`
done

[ "$3" = "" ] || rm ${3}/`hostname`_fdt_${$}
sleep 10